### ISSUE TITLE
Add multi language support

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#11]
The component needs to be translated into various languages. For the first release, the following languages are needed:

- DE
- EN
- Maybe FR → I will clarify this

The translations should be placed in a JSON or YAML file, ie. `de.yml` or `en.json`.

There should also be a simple mechanism to inject additional languages.

@rudigier will take care of this. Thank you! 👍

**Comment by rudigier** [comment]
@jmuheim Habe gestern daran gearbeitet. Leider habe ich keine Berechtigung fürs NothingAG Git-Repo. Daher hier mal einen ersten Entwurf. 
https://github.com/rudigier/adg-components/tree/feature/i18n
Werde die Funktion noch bisschen besser entwickeln - aber als erster preview.

**Comment by rudigier** [comment]
![Bildschirmfoto 2022-04-11 um 08 52 34](https://user-images.githubusercontent.com/3023646/162681217-bf711b32-557b-4b72-8302-704543186531.png)

**Comment by jmuheim** [comment]
Cool, @rudigier! 👍

I sent you an invitation some days ago already, maybe it slipped your attention?

![CleanShot 2022-04-11 at 08 53 35@2x](https://user-images.githubusercontent.com/1814983/162681391-7e680849-da8e-4652-a348-1d726868afe1.png)

**Comment by jmuheim** [comment]
This is done and merged already. Thank you, @rudigier!
