### ISSUE TITLE
Turn off Shadow-DOM

### ISSUE THREAD

**Issue by wmaurer** [NothingAG/adg-components#2]
We have decided that we will turn use Web Components but turn off the Shadow DOM. The advantages of turning off the Shadow DOM are:
* input elements can be associated with a form external to the Shadow DOM
* the individual elements of the Web Component can be customised via CSS externally to the Web Component

Disadvantages that we may or may not have to deal with:
* events that are internal to the Web Component will be propagated (and therefore theoretically handled) external to the Web Component. This breaks the 'black box' concept of the Web Component. There is a workaround: adding extra code (and tests) to stop the propagation. 
* some CSS styles which are critical to accessibility (e.g. display: inline or display: inline-block) may be overridden by external styles, thus breaking the accessibility of the Web Component
* class names are global, therefore a BEM-style naming convention would be recommended

Suggestion:
* let's ignore the event propagation problem. In the big picture, it's rather minor
* guidance for CSS style customisation should be clearly documented so that developers know which styles are critical to accessibility
* implement BEM class names

Request for input from @jmuheim

**Comment by jmuheim** [comment]
> events that are internal to the Web Component will be propagated (and therefore theoretically handled) external to the Web Component. This breaks the 'black box' concept of the Web Component. There is a workaround: adding extra code (and tests) to stop the propagation.
>
> [...]
>
> Suggestion: let's ignore the event propagation problem. In the big picture, it's rather minor

We actually **want** some events to be available outside the component, so the document that displays the component can react to its status changes (ie. events like `option-selected`, `unselect-all`, etc.).

> some CSS styles which are critical to accessibility (e.g. display: inline or display: inline-block) may be overridden by external styles, thus breaking the accessibility of the Web Component

Fortunately, those side-effects are rather small. If people want, they always can break something somewhere. We cannot protect them from themselves. 😋 Still, it's good to be aware of it.

> Suggestion: guidance for CSS style customisation should be clearly documented so that developers know which styles are critical to accessibility

Good point. I'm playing around with attaching CSS-properties that have an effect on semantics to `data-*` attributes, ie. `[data-block]` (to make an element `display: block`) or `[data-visually-hidden]`. Although promising in some respects, I'm not sure whether this could become a globally working approach/pattern. For more infos, see https://github.com/NothingAG/a11y-semantics-css.

At least, we might add a little notice to the README that one should be careful with overriding certain CSS properties.

> class names are global, therefore a BEM-style naming convention would be recommended
>
> Suggestion: implement BEM class names

I don't think we need to stick to the full complexity of BEM, as the general HTML structure of the component is (and will remain) rather simple. Suggestion: let's use a prefix `adg-combobox--` for each class name, then add a self-explaining name for the class, ie. `adg-combobox--options-list`. This leaves the possibility to add further components later on, ie. `adg-datepicker--*`.

**Comment by wmaurer** [comment]
Ok, Shadow DOM has been turned off and the CSS class names all have an adg-combobox-- prefix.
I think this issue can be probably closed now, what do you think @jmuheim?
I'll open a new issue for the documentation about CSS properties.

**Comment by jmuheim** [comment]
Perfect, thank you. I'm closing this.
