### ISSUE TITLE
Bug: When filtering, the screen reader text "starting with XXX" displays non-interpolated I18n value "{first}"

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#25]
To improve usage for screen reader users, when a filter is entered, we announce the first displayed option, so they know whether their filter is already "narrow" enough.

Currently, instead of announcing the option's name (ie. `Badminton`), it just announces `{first}`.

🎬 https://user-images.githubusercontent.com/1814983/165716899-203ab834-732c-4c71-990c-1a5614abdc36.png

This seems to be an I18n interpolation bug, so I assign this to you, @rudigier. Thank you.

**Comment by rudigier** [comment]
@jmuheim Done. Ready for test.

**Comment by jmuheim** [comment]
Thanks you, @rudigier! Validated in #41.
