### ISSUE TITLE
Enhancement: Instead of randomly generating an ID for internal usage, we should use the ID assigned to the component

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#26]
We are currently creating a consecutive number to prevent ID clashes:

> private _id = `adg-combobox-${nextUniqueId++}`;

We need this to create internal IDs, ie. for the filter input: `#adg-combobox-0--input`.

The two components, although created in a clear order, seem to get created in this exact order. So sometimes the first component has id `0`, and sometimes `1` in his IDs. This makes it kind of tricky to write tests.

Why not simply take the `id` that's provided by the developer?

    <adg-combobox id="hobbiesCombobox" name="hobbies"></adg-combobox>

So the ID for the filter would like this: `#hobbiesCombobox--input`. And if no ID is provided, we can still fall back on the existing generator.

**Comment by rudigier** [comment]
@jmuheim Ready for test

**Comment by jmuheim** [comment]
Perfect, thank you!
