### ISSUE TITLE
Bug: "Colours selected" is not translated to German

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#27]
Even though the single select has `lang="de"`, the following string is not translated to German:

![CleanShot 2022-04-28 at 17 52 57@2x](https://user-images.githubusercontent.com/1814983/165793576-b6ab4560-1c37-4190-a011-1e0b096a9674.png)

Let's ignore at the time being that using a plural sentence for a single select does not make sense. At a later stage, we can implement a more sophisticated solution which adapts to singular/plural also for multi-selects, depending on how many options are selected. This would then automatically fix it for single-selects, too.

**Comment by rudigier** [comment]
It's because in the example the attribute filterLabel is set to "Colours"

**Comment by jmuheim** [comment]
Still, I think that `selected` is not a German word, is it? 🤓

**Comment by rudigier** [comment]
fix is inserted

**Comment by jmuheim** [comment]
Thank you, it works! 🚀

![CleanShot 2022-04-29 at 10 09 04@2x](https://user-images.githubusercontent.com/1814983/165907377-50006b9b-8f3d-4edc-9a44-e936d3b9eaf4.png)
