### ISSUE TITLE
Definitive decision on component (widget?) name

### ISSUE THREAD

**Issue by wmaurer** [NothingAG/adg-components#3]
Due to issue #2 we need to stick with BEM class names, and the current class names need to be renamed. This can only be done after the component name has been finalised (I'm deliberately trying to avoid the term widget, since I haven't really used that term since the good old JQuery days of 2013).

My suggestion (after consulting with @jmuheim) is `adg-combobox`. (boring but pragmatic)
Another cool suggestion from Jürgen is `adg-selectly`

@jmuheim can this be decided at the ADG Hackday tomorrow (30.03)?.

**Comment by jmuheim** [comment]
Thanks for your efforts and motivation, @wmaurer. I plan to raise this question tomorrow so we can choose a name with the help of the community.

I agree that we should get rid of the term "widget", both in the current project's name, as well as in the ADG itself.

See you tomorrow!

**Comment by jmuheim** [comment]
Final decisions:

- Our repository (and thus library) name is **adg-components**
    -  Over time, we will replace the term `widget` in the ADG with `component`
- Our single/multi select name is **adg-combobox**
    - Any additional info will be placed prominently in the `README` (ie. searchable/filterable, single/multi, accessible...)

Thanks for all your feedbacks and suggestions, @community! 😊
