### ISSUE TITLE
Remove filter term when clicking "unselect all" button

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#38]
Currently, the filter term remains after clicking "unselect all" button:

🎬 https://user-images.githubusercontent.com/1814983/166093515-e294c64f-7e7c-42b9-a09b-75c1f3b64726.gif

It should be removed completely, for both single and multi select.

**Comment by rudigier** [comment]
@jmuheim Done. Ready for testing.

**Comment by jmuheim** [comment]
While the filter term indeed is removed, the options remain filtered:

![CleanShot 2022-04-30 at 10 54 13@2x](https://user-images.githubusercontent.com/1814983/166098902-7d4692d0-92ae-40ad-b31d-8e1453ca9fef.png)

I think it's a good idea now to start using pull requests again, so our `main` branch remains clean.

I have added a related PR where with corresponding tests, see: #39.

**Comment by jmuheim** [comment]
Reopening this, as there's still a bug, see #39.

**Comment by rudigier** [comment]
@jmuheim Please re-check this issue.

**Comment by jmuheim** [comment]
I'm taking a close look at the filter functionality in general now. Needs some refactoring because of the single select functionality, where the input's value is not always the same as the filter term.

**Comment by jmuheim** [comment]
I inspected this, and I while it works much better now!

What I still feel is suboptimal: when entering a filter in the single select, then choosing an option, I would expect the filter to be reset in the background, so all options would be displayed again when the dropdown is opened. At the time being, the previous filter keeps existing.

![CleanShot 2022-05-02 at 18 09 10](https://user-images.githubusercontent.com/1814983/166267861-2c6f23f6-2695-4f40-b41d-4999ec82359a.gif)

But I think this is good enough for the moment. I've even written a test to document this in f00a474b54ef3121ffe79a86275404b6eb4018d6.
