### ISSUE TITLE
Do not automatically create a label for the combobox

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#40]
I wonder whether it makes sense to automatically create a `<label>` for the combobox. Usually the structure of a page will have the `<label>` somewhere "decoupled" from the combobox itself, ie. with some container around it or similar.

I vote for:

- By default, do not create a `<label>`
- Offer an option to create one anyway, ie. `createLabelTag: true` (default: `false`)

Or should it be the other way round? Create one by default, and allow to disable it manually? 🤔 This way the chance is higher that devs will stumble over the feature by themselves...

**Comment by jmuheim** [comment]
Thinking about this, I feel it would be great if the combobox would check if there's a label on the page that's associated with it:

- If so, it simply accepts its label.
- If not, it triggers a `console.warn()`, complaining about this a11y issue, and offering solutions: "Every form control needs an associated label, see https://a11y-dev.guide/examples/forms/good-example/. If you set option label='My cool combobox', we will create one for you."

**Comment by rudigier** [comment]
@jmuheim Done.

**Comment by jmuheim** [comment]
Great, thank you! 👍

I hope you still get some opportunity to enjoy your weekend... 🥱
