### ISSUE TITLE
Allow single select

### ISSUE THREAD

**Issue by wmaurer** [NothingAG/adg-components#5]
The current accessible-dropdown component is a multi-select, internally backed by `input type="checkbox"`.
A further requirement is to allow the option of single select via an attribute to the Web Component.

First question, what should the attribute be called, and what should the values be? Suggestions:
* type="multi", type="single" (I believe this was suggested by @jmuheim)
* selectionMode="single", selectionModel="multiple" (suggested by @wmaurer 
* multipleselectable="true", multipleselectable="false" (analogous to ARIA listbox)

Further questions:
* What are the accessibility implications of single-select?
* Would the keyboard interactions change between single and multiple select?
* What happens with the chip-list with single-select?

**Comment by jmuheim** [comment]
> First question, what should the attribute be called, and what should the values be?

I opt for a rather short name. What about `multi="true"`? `selectionMode` does not feel like a proper HTML attribute to me (camelcase), and `multipleselectable` just is hard to read and ugly.

> What are the accessibility implications of single-select?

Basically, we just replace the `<input type="checkbox">` elements with `type="radio"` ones.

> Would the keyboard interactions change between single and multiple select?

Most interactions will be exactly the same, with a few exemptions:

- When toggling through the options using `Up`/`Down` arrow, we can rely on the browser standard behaviour (no JavaScript needed to move the focus between inputs)
    - I think it still makes sense to jump to the filter when the last option is reached and `Down` is pressed again, or when the first option is reached and `Up` is pressed again.
- With checkboxes, when the focus is moved, no option is checked automatically: one has to press `Space` (or sometimes `Enter`) to toggle the input. In contrast to this, when toggling through radio buttons, the current option is automatically checked. To confirm the choice, we should listen to the `click` event, which then would simply close the options list.
- As only one option can be selected, some of the (visually hidden) help texts need to be changed, ie. when announcing how many options are selected. Also, the counter of the `X` button is not necessary anymore. And obviously, the pills/tags should not be displayed.
> What happens with the chip-list with single-select?

What do you mean with "chip-list"?

**Comment by wmaurer** [comment]
> What do you mean with "chip-list"?

By chip-list I mean the Pills/Tags (material design calls them chips: https://material.io/components/chips#types)
Do we need the Pills/Tags with single select?

**Comment by jmuheim** [comment]
> As you have said above the pills/tags should not be displayed with single-select.

Exactly, they are not needed for single select.

**Comment by wmaurer** [comment]
>   * I think it still makes sense to jump to the filter when the last option is reached and `Down` is pressed again, or when the first option is reached and `Up` is pressed again.

Easy to do with a couple lines of code, but it's overriding the standard browser behaviour ;-)

> And obviously, the pills/tags should not be displayed.

So the value simply gets copied into the input text box, right? I guess that's the only visual indication of which value was selected ...

**Comment by jmuheim** [comment]
> > I think it still makes sense to jump to the filter when the last option is reached and Down is pressed again, or when the first option is reached and Up is pressed again.
> 
> Easy to do with a couple lines of code, but it's overriding the standard browser behaviour ;-)

You're a tough challenger! 😋 I like that. And yes, I know, it's overriding standard browser behaviour. Let me explain a bit more about the situation.

The reason for focusing the filter after the last option is focused is that this way screen reader users know that the search wrapped around. As checkboxes are not seen as a "group" of elements, they are announced by screen readers simply with their label only - in contrast to radio buttons that are announced with their label PLUS "option X of Y". So for radio buttons, I just realised, we would not need a way to indicate the search wrapped around, as the screen reader will announce it explicitly. 🤔

Another way of achieving this was to use `ul { list-style-type: decimal }` for the `<ul>` in which the checkboxes reside (and making those decimal numbers invisible using `li { color: transparent }`). This way, most screen readers would announce the `<li>`'s number. But this has the drawback that this number is treated as a `block` element, which makes NVDA and JAWS stop after the number, and requires another `down` key press to announce the label of the checkbox. So the `down` key must be pressed twice for each option, which doesn't feel right to me (even though it's NVDA/JAWS standard behaviour). And in this scenario, with radio buttons we would probably have announced both the `<li>`'s number plus the radio button's "X of Y" numbers, which would be redundant (didn't test this yet though).

I'm not completely happy with all of this yet. Let's keep it the way it is for now (focus the filter), even though it's overriding standard browser behaviour. One additional benefit of this is that certain users who might not be aware that they can always type in characters for changing the filter (regardless whether the filter is focused or not) will reach the filter every now and then when toggling through the options.

**Comment by jmuheim** [comment]
In the meantime, a first single-select version was implemented:

https://github.com/NothingAG/adg-components/pull/15

It was a bit buggy, so we are in the process of re-writing it now, backed up by automated tests.

Closing this.
