### ISSUE TITLE
"Detach" CSS from component → make it easily customisable

### ISSUE THREAD

**Issue by jmuheim** [NothingAG/adg-components#51]
Currently, when loading the component inside a page, it attaches all its CSS at the very end of the `<head>`:

![CleanShot 2022-05-10 at 14 50 02@2x](https://user-images.githubusercontent.com/1814983/167632689-40100068-dea5-40ab-bb25-2a53f658364a.png)

This means, it is loaded after any other `<style>`, which makes it hard to overwrite these individual styles (without ugly `!important`).

There must be a way to change this. Stencil probably offers some configuration that ie. either decouples the styles completely from the component (so the devs can load them manually), or that loads them **not as the last element** inside `<head>` (but ie. directly after the `<script>` tag).

My shot into the blue is that the current settings kind of mimic the behaviour of a web component with Shadow DOM enabled, ie. creating a situation where the styles should not be overridden "from the outside" at all.

@wmaurer, as you already use Stencil in production, could you give us some insights here, please?

**Comment by jmuheim** [comment]
I added a question on StackOverflow: https://stackoverflow.com/questions/72194542/stenciljs-how-to-prevent-css-from-being-auto-appended-to-bottom-of-head

**Comment by jmuheim** [comment]
UPDATE: Wayne is working on this today and/or tomorrow. ✅

**Comment by wmaurer** [comment]
It took me a long time to figure this out, but the answer is here:
https://stackoverflow.com/a/72203709/664533

And the fix is here 521a3c1ca8f03e78129627ae6cbcbe2ba48d768c

**Comment by jmuheim** [comment]
It's incredible how much time sometimes is needed for such little changes that yield so much.

Thanks from the bottom of my heart for your effort, @wmaurer! I will keep this open until I verified it and added it to the documentation. 👍

**Comment by jmuheim** [comment]
Verified it, added info to README. Closing this.
