### ISSUE TITLE
Pre-set checked value(s) when initialising combobox

### ISSUE THREAD

**Issue by wmaurer** [NothingAG/adg-components#6]
There is currently no way to pre-specify the selected values of the accessible-dropdown. An input would be required to set an initial value.

**Comment by jmuheim** [comment]
> There is currently no way to pre-specify the selected values of the accessible-dropdown. An input would be required to set an initial value.

Definitely. Maybe some day we can do it like that:

```html
<adg-combobox multi="true">
  <adg-combobox-option value="1" selected="true">
    Hiking
  </adg-combobox-option>
  <adg-combobox-option value="2">
    Soccer
  </adg-combobox-option>
</adg-combobox>
```

But until then, we could just provide a flag in the array of option objects:

```
[{key: 1, value: "Hiking", selected: true},
{key: 2, value: "Soccer"}]
```

**Comment by jmuheim** [comment]
> A corresponding event to notify clients when the selected value has changed will also be very useful to aid with the integration with client-side frameworks like Vue, React and Angular.

I added a separate issue for this:

https://github.com/NothingAG/adg-components/issues/10

**Comment by jmuheim** [comment]
@rudigier As far as I know you have taken care of letting values to be checked on init. Can you give an update here? I will then update the README.

**Comment by wmaurer** [comment]
Ok, ready to test

**Comment by jmuheim** [comment]
Looks good to me.

Tested in b6e0bd257c55b18268c80910e02e591f7d1d2360.
