### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by wmaurer** [NothingAG/adg-components#7]
The current project, as an Nx workspace with a StencilJs plugin should work out of the box with Jest and Puppeteer.

Cypress would be a better (more modern) alternative to Puppeteer.

Which direction should go with the testing? Is one framework (e.g. Cypress) good enough for all of our testing purposes? How good is it with reading visually hidden elements and aria-live regions?

I believe we have a testing expert on board; I look forward to Ramon's input :-)

**Comment by jmuheim** [comment]
@ramonwenger Could you please give an update about this? Thank you. 🙏

**Comment by jmuheim** [comment]
Quite a few tests were added in the meantime:

- https://github.com/NothingAG/adg-components/pull/22
- https://github.com/NothingAG/adg-components/pull/28

More tests will be added soon, especially for the single select functionality.
