### ISSUE TITLE
Node version management

### ISSUE THREAD

**Issue by ramonwenger** [NothingAG/adg-components#9]
When checking out the repo locally, I was not sure which node version to use. 

I would suggest fixing the node version somewhere, for example with a `.tool-versions` file at the root (used by [asdf](https://asdf-vm.com/manage/configuration.html#tool-versions))

**Comment by wmaurer** [comment]
Ii'm not sure if a real cross-tool compatible way of fixing the node version (e.g. I use nvmrc, which uses a different configuration file to asdf).

Another possibility is to define the node version range in package.json:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

e.g.:
```
  "engines": {
    "node": ">=16"
  }
```

Then `npm install` would give a warning if a version of node lower than 16 is used.

**Comment by jmuheim** [comment]
I added an `.nvmrc` file, see https://github.com/NothingAG/adg-components/pull/30.

I think this fixes the issue? Or is it now "doppelt gemoppelt" (two different solutions for the same thing)?
